# Generalize Niche Genres
subgenre_to_general_genre = {
    'a cappella': 'Others',
    'abstract': 'Experimental',
    'abstract beats': 'Electronic',
    'abstract hip hop': 'Experimental',
    'abstract idm': 'Electronic',
    'abstractro': 'Experimental',
    'accordion': 'Others',
    'acid house': 'Electronic',
    'acid jazz': 'Jazz',
    'acid techno': 'Electronic',
    'acousmatic': 'Experimental',
    'acoustic blues': 'RnB/Soul',
    'acoustic pop': 'Pop',
    'adult standards': 'Others',
    'african percussion': 'Others',
    'african rock': 'Rock',
    'afrikaans': 'Others',
    'afrobeat': 'Funk',
    'afrobeats': 'Funk',
    'aggrotech': 'Electronic',
    'albanian pop': 'Pop',
    'album rock': 'Rock',
    'albuquerque indie': 'Indie',
    'alternative americana': 'Country/Folk',
    'alternative country': 'Country/Folk',
    'alternative dance': 'Electronic',
    'alternative emo': 'Rock',
    'alternative hardcore': 'Rock',
    'alternative hip hop': 'Hip-Hop',
    'alternative metal': 'Rock',
    'alternative metalcore': 'Rock',
    'alternative new age': 'Experimental',
    'alternative pop': 'Pop',
    'alternative pop rock': 'Rock',
    'alternative r&b': 'RnB/Soul',
    'alternative rock': 'Rock',
    'alternative roots rock': 'Rock',
    'ambeat': 'Electronic',
    'ambient': 'Electronic',
    'ambient dub techno': 'Electronic',
    'ambient fusion': 'Electronic',
    'ambient idm': 'Electronic',
    'ambient psychill': 'Electronic',
    'ambient trance': 'Electronic',
    'anarcho-punk': 'Rock',
    'andean': 'Others',
    'anime': 'Others',
    'anime score': 'Soundtracks',
    'anti-folk': 'Indie',
    'antiviral pop': 'Pop',
    'appalachian folk': 'Country/Folk',
    'arab folk': 'Country/Folk',
    'arab pop': 'Pop',
    'arabesk': 'Others',
    'argentine indie': 'Indie',
    'argentine reggae': 'Others',
    'argentine rock': 'Rock',
    'armenian folk': 'Others',
    'art rock': 'Rock',
    'athens indie': 'Indie',
    'atmospheric black metal': 'Rock',
    'atmospheric post rock': 'Rock',
    'atmospheric post-metal': 'Rock',
    'aussietronica': 'Electronic',
    'austindie': 'Indie',
    'australian alternative rock': 'Rock',
    'australian country': 'Country/Folk',
    'australian dance': 'Electronic',
    'australian hip hop': 'Hip-Hop',
    'australian indie': 'Indie',
    'australian pop': 'Pop',
    'austrian hip hop': 'Hip-Hop',
    'austropop': 'Pop',
    'avant-garde': 'Experimental',
    'avant-garde jazz': 'Jazz',
    'avantgarde metal': 'Rock',
    'axe': 'Others',
    'azonto': 'Others',
    'bachata': 'Others',
    'baile funk': 'Funk',
    'balearic': 'Electronic',
    'balkan brass': 'Others',
    'banda': 'Others',
    'bangla': 'Others',
    'barbershop': 'Others',
    'barnemusikk': 'Others',
    'barnmusik': 'Others',
    'baroque': 'Classical',
    'baroque ensemble': 'Classical',
    'basque rock': 'Rock',
    'bass music': 'Electronic',
    'bass trip': 'Electronic',
    'bassline': 'Electronic',
    'bay area hip hop': 'Hip-Hop',
    'beach music': 'Others',
    'beatdown': 'Rock',
    'beats & rhymes': 'Hip-Hop',
    'bebop': 'Jazz',
    'belgian indie': 'Indie',
    'belgian rock': 'Rock',
    'belly dance': 'Others',
    'belorush': 'Others',
    'bemani': 'Others',
    'benga': 'Others',
    'bhangra': 'Others',
    'big band': 'Jazz',
    'big beat': 'Electronic',
    'big room': 'Electronic',
    'black death': 'Rock',
    'black metal': 'Rock',
    'black sludge': 'Rock',
    'black thrash': 'Rock',
    'blackgaze': 'Rock',
    'blaskapelle': 'Others',
    'bluegrass': 'Country/Folk',
    'blues': 'Jazz',
    'blues-rock': 'Jazz',
    'blues-rock guitar':'Jazz',
    'bmore': 'Others',
    'bolero': 'Others',
    'boogaloo': 'Others',
    'boogie-woogie': 'Others',
    'bossa nova': 'Jazz',
    'bossa nova jazz': 'Jazz',
    'boston rock': 'Rock',
    'bounce': 'Hip-Hop',
    'bouncy house': 'Electronic',
    'bow pop': 'Pop',
    'boy band': 'Pop',
    'brass band': 'Others',
    'brass ensemble': 'Others',
    'brazilian composition': 'Others',
    'brazilian gospel': 'Others',
    'brazilian hip hop': 'Hip-Hop',
    'brazilian indie': 'Indie',
    'brazilian pop music': 'Pop',
    'brazilian punk': 'Rock',
    'breakbeat': 'Electronic',
    'breakcore': 'Electronic',
    'breaks': 'Electronic',
    'brega': 'Others',
    'breton folk': 'Country/Folk',
    'brill building pop': 'Pop',
    'british alternative rock': 'Rock',
    'british blues': 'Jazz',
    'british brass band': 'Others',
    'british dance band': 'Others',
    'british folk': 'Country/Folk',
    'british indie rock': 'Indie',
    'british invasion': 'Rock',
    'britpop': 'Pop',
    'broadway': 'Others',
    'broken beat': 'Others',
    'brooklyn indie': 'Indie',
    'brostep': 'Electronic',
    'brutal death metal': 'Rock',
    'brutal deathcore': 'Rock',
    'bubble trance': 'Electronic',
    'bubblegum dance': 'Pop',
    'bubblegum pop': 'Pop',
    'bulgarian rock': 'Rock',
    'byzantine': 'Others',
    'c-pop': 'Pop',
    'c64': 'Others',
    'c86': 'Indie',
    'cabaret': 'Others',
    'cajun': 'Others',
    'calypso': 'Others',
    'canadian country': 'Country/Folk',
    'canadian hip hop': 'Hip-Hop',
    'canadian indie': 'Indie',
    'canadian metal': 'Rock',
    'canadian pop': 'Pop',
    'candy pop': 'Pop',
    'cantautor': 'Others',
    'cante flamenco': 'Others',
    'canterbury scene': 'Rock',
    'cantopop': 'Pop',
    'canzone napoletana': 'Others',
    'capoeira': 'Others',
    'carnatic': 'Classical',
    'catstep': 'Electronic',
    'caucasian folk': 'Country/Folk',
    'ccm': 'Others',
    'ceilidh': 'Others',
    'cello': 'Classical',
    'celtic': 'Country/Folk',
    'celtic christmas': 'Others',
    'celtic punk': 'Rock',
    'celtic rock': 'Rock',
    'central asian folk': 'Country/Folk',
    'chalga': 'Others',
    'chamber pop': 'Indie',
    'chanson': 'Others',
    'chanson quebecois': 'Others',
    'chaotic black metal': 'Rock',
    'chaotic hardcore': 'Rock',
    'charred death': 'Rock',
    'chicago blues': 'Jazz',
    'chicago house': 'Electronic',
    'chicago indie': 'Indie',
    'chicago soul': 'RnB/Soul',
    'chicano rap': 'Hip-Hop',
    'children\'s christmas': 'Others',
    'children\'s music': 'Others',
    'chilean rock': 'Rock',
    'chill groove': 'Electronic',
    'chill lounge': 'Electronic',
    'chill-out': 'Electronic',
    'chill-out trance': 'Electronic',
    'chillstep': 'Electronic',
    'chillwave': 'Electronic',
    'chinese indie rock': 'Rock',
    'chinese opera': 'Classical',
    'chinese traditional': 'Classical',
    'chip hop': 'Hip-Hop',
    'chiptune': 'Electronic',
    'choral': 'Classical',
    'choro': 'Others',
    'christian alternative rock': 'Rock',
    'christian christmas': 'Others',
    'christian dance': 'Electronic',
    'christian hardcore': 'Rock',
    'christian hip hop': 'Hip-Hop',
    'christian metal': 'Rock',
    'christian music': 'Others',
    'christian punk': 'Rock',
    'christian rock': 'Rock',
    'christmas': 'Others',
    'christmas product': 'Others',
    'cinematic dubstep': 'Electronic',
    'clarinet': 'Classical',
    'classic afrobeat': 'Funk',
    'classic belgian pop': 'Pop',
    'classic chinese pop': 'Pop',
    'classic colombian pop': 'Pop',
    'classic czech pop': 'Pop',
    'classic danish pop': 'Pop',
    'classic dutch pop': 'Pop',
    'classic eurovision': 'Others',
    'classic finnish pop': 'Pop',
    'classic finnish rock': 'Rock',
    'classic french pop': 'Pop',
    'classic funk rock': 'Funk',
    'classic garage rock': 'Rock',
    'classic italian pop': 'Pop',
    'classic norwegian pop': 'Pop',
    'classic peruvian pop': 'Pop',
    'classic polish pop': 'Pop',
    'classic psychedelic rock': 'Rock',
    'classic rock': 'Rock',
    'classic russian pop': 'Pop',
    'classic russian rock': 'Rock',
    'classic schlager': 'Others',
    'classic soundtrack': 'Soundtracks',
    'classic swedish pop': 'Pop',
    'classic turkish pop': 'Pop',
    'classic venezuelan pop': 'Pop',
    'classical': 'Classical',
    'classical christmas': 'Classical',
    'classical flute': 'Classical',
    'classical guitar': 'Classical',
    'classical organ': 'Classical',
    'classical performance': 'Classical',
    'classical period': 'Classical',
    'classical piano': 'Classical',
    'college a cappella': 'Others',
    'college marching band': 'Others',
    'colombian rock': 'Rock',
    'columbus ohio indie': 'Indie',
    'comedy': 'Others',
    'comedy rock': 'Rock',
    'comic': 'Others',
    'commons': 'Others',
    'complextro': 'Electronic',
    'composition d': 'Others',
    'concert piano': 'Classical',
    'consort': 'Classical',
    'contemporary classical': 'Classical',
    'contemporary country': 'Country/Folk',
    'contemporary folk': 'Country/Folk',
    'contemporary jazz': 'Jazz',
    'contemporary post-bop': 'Jazz',
    'cool jazz': 'Jazz',
    'corrosion': 'Others',
    'corsican folk': 'Country/Folk',
    'country': 'Country/Folk',
    'country blues': 'Country/Folk',
    'country christmas': 'Country/Folk',
    'country dawn': 'Country/Folk',
    'country gospel': 'Country/Folk',
    'country road': 'Country/Folk',
    'country rock': 'Country/Folk',
    'coupe decale': 'Others',
    'coverchill': 'Others',
    'covertrance': 'Others',
    'cowboy western': 'Others',
    'cowpunk': 'Rock',
    'crack rock steady': 'Rock',
    'croatian pop': 'Pop',
    'crossover prog': 'Rock',
    'crossover thrash': 'Rock',
    'crunk': 'Hip-Hop',
    'crust punk': 'Rock',
    'cryptic black metal': 'Rock',
    'cuban rumba': 'Others',
    'cubaton': 'Others',
    'cumbia': 'Others',
    'cumbia funk': 'Funk',
    'cumbia sonidera': 'Others',
    'cumbia villera': 'Others',
    'cyber metal': 'Rock',
    'czech folk': 'Country/Folk',
    'czech rock': 'Rock',
    'dallas indie': 'Indie',
    'dance pop': 'Pop',
    'dance rock': 'Rock',
    'dance-punk': 'Rock',
    'dancehall': 'Others',
    'dangdut': 'Others',
    'danish hip hop': 'Hip-Hop',
    'danish indie': 'Indie',
    'danish jazz': 'Jazz',
    'danish pop': 'Pop',
    'danish pop rock': 'Rock',
    'dansband': 'Others',
    'danseband': 'Others',
    'dansktop': 'Others',
    'dark ambient': 'Experimental',
    'dark black metal': 'Rock',
    'dark cabaret': 'Others',
    'dark electro-industrial': 'Electronic',
    'dark hardcore': 'Rock',
    'dark jazz': 'Jazz',
    'dark minimal techno': 'Electronic',
    'dark progressive house': 'Electronic',
    'dark psytrance': 'Electronic',
    'dark wave': 'Others',
    'darkstep': 'Electronic',
    'death core': 'Rock',
    'death metal': 'Rock',
    'deathgrind': 'Rock',
    'deep acoustic pop': 'Pop',
    'deep adult standards': 'Others',
    'deep alternative r&b': 'RnB/Soul',
    'deep ambient': 'Electronic',
    'deep baroque': 'Classical',
    'deep brazilian pop': 'Pop',
    'deep breakcore': 'Electronic',
    'deep canadian indie': 'Indie',
    'deep ccm': 'Others',
    'deep cello': 'Classical',
    'deep chill': 'Electronic',
    'deep chill-out': 'Electronic',
    'deep christian rock': 'Rock',
    'deep classic garage rock': 'Rock',
    'deep classical piano': 'Classical',
    'deep comedy': 'Others',
    'deep contemporary country': 'Country/Folk',
    'deep dance pop': 'Pop',
    'deep darkpsy': 'Electronic',
    'deep deep house': 'Electronic',
    'deep deep tech house': 'Electronic',
    'deep delta blues': 'Jazz',
    'deep disco': 'Electronic',
    'deep disco house': 'Electronic',
    'deep discofox': 'Others',
    'deep downtempo fusion': 'Electronic',
    'deep dub techno': 'Electronic',
    'deep east coast hip hop': 'Hip-Hop',
    'deep euro house': 'Electronic',
    'deep eurodance': 'Electronic',
    'deep filthstep': 'Electronic',
    'deep flow': 'Others',
    'deep folk metal': 'Rock',
    'deep free jazz': 'Jazz',
    'deep freestyle': 'Others',
    'deep full on': 'Others',
    'deep funk': 'Funk',
    'deep funk house': 'Funk',
    'deep g funk': 'Funk',
    'deep german indie': 'Indie',
    'deep german punk': 'Rock',
    'deep gothic post-punk': 'Rock',
    'deep happy hardcore': 'Electronic',
    'deep hardcore': 'Rock',
    'deep hardcore punk': 'Rock',
    'deep hardstyle': 'Electronic',
    'deep house': 'Electronic',
    'deep indian pop': 'Pop',
    'deep indie pop': 'Indie',
    'deep indie rock': 'Indie',
    'deep indie singer-songwriter': 'Indie',
    'deep italo disco': 'Electronic',
    'deep jazz fusion': 'Jazz',
    'deep jazz guitar': 'Jazz',
    'deep jazz piano': 'Jazz',
    'deep latin alternative': 'Others',
    'deep liquid': 'Electronic',
    'deep liquid bass': 'Electronic',
    'deep melodic death metal': 'Rock',
    'deep melodic hard rock': 'Rock',
    'deep melodic house': 'Electronic',
    'deep melodic metalcore': 'Rock',
    'deep minimal techno': 'Electronic',
    'deep motown': 'RnB/Soul',
    'deep neo-synthpop': 'Pop',
    'deep neofolk': 'Country/Folk',
    'deep new wave': 'Pop',
    'deep nordic folk': 'Country/Folk',
    'deep northern soul': 'RnB/Soul',
    'deep opera': 'Classical',
    'deep orchestral': 'Classical',
    'deep orgcore': 'Rock',
    'deep pop emo': 'Rock',
    'deep pop punk': 'Rock',
    'deep power-pop punk': 'Rock',
    'deep progressive house': 'Electronic',
    'deep progressive trance': 'Electronic',
    'deep psychobilly': 'Rock',
    'deep psytrance': 'Electronic',
    'deep punk rock': 'Rock',
    'deep ragga': 'Others',
    'deep rai': 'Others',
    'deep regional mexican': 'Others',
    'deep smooth jazz': 'Jazz',
    'deep soft rock': 'Rock',
    'deep soul house': 'Electronic',
    'deep soundtrack': 'Soundtracks',
    'deep southern soul': 'RnB/Soul',
    'deep space rock': 'Rock',
    'deep string quartet': 'Classical',
    'deep sunset lounge': 'Electronic',
    'deep surf music': 'Others',
    'deep symphonic black metal': 'Rock',
    'deep talent show': 'Others',
    'deep tech house': 'Electronic',
    'deep thrash metal': 'Rock',
    'deep trap': 'Hip-Hop',
    'deep turkish pop': 'Pop',
    'deep uplifting trance': 'Electronic',
    'deep vocal house': 'Electronic',
    'deep vocal jazz': 'Jazz',
    'delta blues': 'Jazz',
    'demoscene': 'Others',
    'denver indie': 'Indie',
    'depressive black metal': 'Rock',
    'desert blues': 'Jazz',
    'desi': 'Others',
    'destroy techno': 'Electronic',
    'detroit hip hop': 'Hip-Hop',
    'detroit techno': 'Electronic',
    'didgeridoo': 'Others',
    'digital hardcore': 'Electronic',
    'dirty south rap': 'Hip-Hop',
    'dirty texas rap': 'Hip-Hop',
    'disco': 'Pop',
    'disco house': 'Electronic',
    'discofox': 'Others',
    'dixieland': 'Jazz',
    'djent': 'Rock',
    'dominican pop': 'Pop',
    'doo-wop': 'Others',
    'doom metal': 'Rock',
    'doomcore': 'Rock',
    'doujin': 'Others',
    'downtempo': 'Electronic',
    'downtempo fusion': 'Electronic',
    'downtempo trip hop': 'Electronic',
    'drama': 'Others',
    'dream pop': 'Pop',
    'dreamo': 'Others',
    'drill and bass': 'Electronic',
    'drone': 'Others',
    'drone folk': 'Country/Folk',
    'drone metal': 'Rock',
    'drone psych': 'Others',
    'drum and bass': 'Electronic',
    'drumfunk': 'Electronic',
    'dub': 'Others',
    'dub techno': 'Electronic',
    'dubstep': 'Electronic',
    'dubstep product': 'Others',
    'dubsteppe': 'Others',
    'duranguense': 'Others',
    'dutch hip hop': 'Hip-Hop',
    'dutch house': 'Electronic',
    'dutch pop': 'Pop',
    'dutch rock': 'Rock',
    'e6fi': 'Others',
    'early music': 'Classical',
    'early music ensemble': 'Classical',
    'east coast hip hop': 'Hip-Hop',
    'easy listening': 'Others',
    'ebm': 'Electronic',
    'ectofolk': 'Country/Folk',
    'ecuadoria': 'Others',
    'edm': 'Electronic',
    'electric blues': 'RnB/Soul',
    'electro': 'Electronic',
    'electro dub': 'Electronic',
    'electro house': 'Electronic',
    'electro jazz': 'Jazz',
    'electro latino': 'Electronic',
    'electro swing': 'Electronic',
    'electro trash': 'Electronic',
    'electro-industrial': 'Electronic',
    'electroacoustic improvisation': 'Experimental',
    'electroclash': 'Electronic',
    'electrofox': 'Electronic',
    'electronic': 'Electronic',
    'electronica': 'Electronic',
    'electronicore': 'Electronic',
    'electropowerpop': 'Pop',
    'electropunk': 'Electronic',
    'emo': 'Rock',
    'emo punk': 'Rock',
    'enka': 'Others',
    'entehno': 'Others',
    'environmental': 'Others',
    'epicore': 'Others',
    'estonian pop': 'Pop',
    'ethereal gothic': 'Others',
    'ethereal wave': 'Others',
    'etherpop': 'Pop',
    'ethiopian pop': 'Pop',
    'eurobeat': 'Electronic',
    'eurodance': 'Electronic',
    'europop': 'Pop',
    'euroska': 'Others',
    'eurovision': 'Others',
    'exotica': 'Others',
    'experimental': 'Experimental',
    'experimental dubstep': 'Electronic',
    'experimental psych': 'Experimental',
    'experimental rock': 'Rock',
    'fado': 'Others',
    'fake': 'Others',
    'fallen angel': 'Others',
    'faroese pop': 'Pop',
    'fast melodic punk': 'Rock',
    'fidget house': 'Electronic',
    'filmi': 'Others',
    'filter house': 'Electronic',
    'filthstep': 'Electronic',
    'fingerstyle': 'Others',
    'finnish hardcore': 'Rock',
    'finnish hip hop': 'Hip-Hop',
    'finnish indie': 'Indie',
    'finnish jazz': 'Jazz',
    'finnish metal': 'Rock',
    'finnish pop': 'Pop',
    'flamenco': 'Others',
    'flick hop': 'Hip-Hop',
    'folk': 'Country/Folk',
    'folk christmas': 'Country/Folk',
    'folk metal': 'Rock',
    'folk punk': 'Rock',
    'folk rock': 'Rock',
    'folk-pop': 'Pop',
    'folk-prog': 'Rock',
    'folklore argentino': 'Others',
    'folkmusik': 'Others',
    'footwork': 'Electronic',
    'forro': 'Others',
    'fourth world': 'Others',
    'freak folk': 'Indie',
    'freakbeat': 'Rock',
    'free improvisation': 'Experimental',
    'free jazz': 'Jazz',
    'freestyle': 'Hip-Hop',
    'french folk': 'Country/Folk',
    'french folk pop': 'Pop',
    'french hip hop': 'Hip-Hop',
    'french indie pop': 'Pop',
    'french movie tunes': 'Soundtracks',
    'french pop': 'Pop',
    'french punk': 'Rock',
    'french reggae': 'Others',
    'french rock': 'Rock',
    'full on': 'Electronic',
    'funeral doom': 'Rock',
    'funk': 'Funk',
    'funk carioca': 'Funk',
    'funk metal': 'Rock',
    'funk rock': 'Funk',
    'funky breaks': 'Electronic',
    'future ambient': 'Electronic',
    'future garage': 'Electronic',
    'futurepop': 'Electronic',
    'g funk': 'Hip-Hop',
    'gabba': 'Electronic',
    'galego': 'Others',
    'gamecore': 'Electronic',
    'gamelan': 'Others',
    'gangster rap': 'Hip-Hop',
    'garage pop': 'Pop',
    'garage punk': 'Rock',
    'garage punk blues': 'Rock',
    'garage rock': 'Rock',
    'gauze pop': 'Pop',
    'gbvfi': 'Indie',
    'geek folk': 'Folk',
    'geek rock': 'Rock',
    'german ccm': 'Others',
    'german hip hop': 'Hip-Hop',
    'german indie': 'Indie',
    'german metal': 'Rock',
    'german oi': 'Rock',
    'german pop': 'Pop',
    'german pop rock': 'Pop',
    'german punk': 'Rock',
    'german show tunes': 'Others',
    'german techno': 'Electronic',
    'ghettotech': 'Electronic',
    'ghoststep': 'Electronic',
    'girl group': 'Pop',
    'glam metal': 'Rock',
    'glam rock': 'Rock',
    'glitch': 'Electronic',
    'glitch beats': 'Electronic',
    'glitch hop': 'Electronic',
    'glitter trance': 'Electronic',
    'goa trance': 'Electronic',
    'goregrind': 'Rock',
    'gospel': 'Others',
    'gospel blues': 'Jazz',
    'gospel reggae': 'Others',
    'gothic alternative': 'Rock',
    'gothic americana': 'Rock',
    'gothic doom': 'Rock',
    'gothic metal': 'Rock',
    'gothic post-punk': 'Rock',
    'gothic rock': 'Rock',
    'gothic symphonic metal': 'Rock',
    'grave wave': 'Others',
    'greek hip hop': 'Hip-Hop',
    'greek house': 'Electronic',
    'greek indie': 'Indie',
    'grim death metal': 'Rock',
    'grime': 'Hip-Hop',
    'grindcore': 'Rock',
    'grisly death metal': 'Rock',
    'groove metal': 'Rock',
    'grunge': 'Rock',
    'grunge pop': 'Pop',
    'grupera': 'Others',
    'guidance': 'Others',
    'gypsy jazz': 'Jazz',
    'hands up': 'Electronic',
    'happy hardcore': 'Electronic',
    'hard alternative': 'Rock',
    'hard bop': 'Jazz',
    'hard glam': 'Rock',
    'hard house': 'Electronic',
    'hard rock': 'Rock',
    'hard stoner rock': 'Rock',
    'hard trance': 'Electronic',
    'hardcore': 'Rock',
    'hardcore breaks': 'Electronic',
    'hardcore hip hop': 'Hip-Hop',
    'hardcore punk': 'Rock',
    'hardcore techno': 'Electronic',
    'hardstyle': 'Electronic',
    'harmonica blues': 'Jazz',
    'harp': 'Classical',
    'hatecore': 'Rock',
    'hauntology': 'Others',
    'hawaiian': 'Others',
    'healing': 'Others',
    'heavy alternative': 'Rock',
    'heavy christmas': 'Others',
    'heavy gothic rock': 'Rock',
    'hi nrg': 'Electronic',
    'highlife': 'Others',
    'hindustani classical': 'Classical',
    'hip hop': 'Hip-Hop',
    'hip hop quebecois': 'Hip-Hop',
    'hip hop tuga': 'Hip-Hop',
    'hip house': 'Electronic',
    'hip pop': 'Pop',
    'hiplife': 'Hip-Hop',
    'hoerspiel': 'Others',
    'hollywood': 'Others',
    'honky tonk': 'Country/Folk',
    'horror punk': 'Rock',
    'horrorcore': 'Hip-Hop',
    'house': 'Electronic',
    'hungarian hip hop': 'Hip-Hop',
    'hungarian pop': 'Pop',
    'hungarian rock': 'Rock',
    'hurban': 'Others',
    'hyphy': 'Hip-Hop',
    'icelandic pop': 'Pop',
    'idol': 'Others',
    'illbient': 'Electronic',
    'indian classical': 'Classical',
    'indian pop': 'Pop',
    'indian rock': 'Rock',
    'indie christmas': 'Indie',
    'indie dream pop': 'Indie',
    'indie emo': 'Indie',
    'indie emo rock': 'Indie',
    'indie folk': 'Indie',
    'indie fuzzpop': 'Indie',
    'indie pop': 'Indie',
    'indie pop rock': 'Indie',
    'indie post-punk': 'Indie',
    'indie psych-pop': 'Indie',
    'indie r&b': 'Indie',
    'indie rock': 'Indie',
    'indie shoegaze': 'Indie',
    'indie singer-songwriter': 'Indie',
    'indietronica': 'Indie',
    'indonesian indie': 'Indie',
    'indonesian pop': 'Pop',
    'indorock': 'Rock',
    'industrial': 'Electronic',
    'industrial metal': 'Rock',
    'industrial rock': 'Rock',
    'instrumental post rock': 'Rock',
    'intelligent dance music': 'Electronic',
    'irish folk': 'Country/Folk',
    'irish indie': 'Indie',
    'irish rock': 'Rock',
    'iskelma': 'Others',
    'islamic recitation': 'Others',
    'israeli rock': 'Rock',
    'italian disco': 'Pop',
    'italian folk': 'Others',
    'italian hip hop': 'Hip-Hop',
    'italian indie pop': 'Pop',
    'italian jazz': 'Jazz',
    'italian pop': 'Pop',
    'italian pop rock': 'Pop',
    'italian progressive rock': 'Rock',
    'italian punk': 'Rock',
    'italo dance': 'Electronic',
    'j-alt': 'Rock',
    'j-ambient': 'Electronic',
    'j-core': 'Electronic',
    'j-dance': 'Pop',
    'j-idol': 'Pop',
    'j-indie': 'Indie',
    'j-metal': 'Rock',
    'j-pop': 'Pop',
    'j-poppunk': 'Rock',
    'j-poprock': 'Rock',
    'j-punk': 'Rock',
    'j-rap': 'Hip-Hop',
    'j-rock': 'Rock',
    'j-theme': 'Others',
    'jam band': 'Rock',
    'jangle pop': 'Pop',
    'jangle rock': 'Rock',
    'japanese jazztronica': 'Jazz',
    'japanese psychedelic': 'Rock',
    'japanese r&b': 'RnB/Soul',
    'japanese standards': 'Others',
    'japanese traditional': 'Others',
    'japanoise': 'Experimental',
    'jazz': 'Jazz',
    'jazz bass': 'Jazz',
    'jazz blues': 'Jazz',
    'jazz brass': 'Jazz',
    'jazz christmas': 'Jazz',
    'jazz funk': 'Jazz',
    'jazz fusion': 'Jazz',
    'jazz metal': 'Jazz',
    'jazz orchestra': 'Jazz',
    'jazz trio': 'Jazz',
    'jerk': 'Hip-Hop',
    'jig and reel': 'Others',
    'judaica': 'Others',
    'jug band': 'Others',
    'juggalo': 'Others',
    'jump blues': 'Jazz',
    'jump up': 'Electronic',
    'jumpstyle': 'Electronic',
    'jungle': 'Electronic',
    'k-hop': 'Hip-Hop',
    'k-indie': 'Indie',
    'k-pop': 'Pop',
    'k-rock': 'Rock',
    'kabarett': 'Others',
    'karneval': 'Others',
    'kc indie': 'Indie',
    'kindermusik': 'Others',
    'kirtan': 'Others',
    'kiwi rock': 'Rock',
    'kizomba': 'Others',
    'klapa': 'Others',
    'klezmer': 'Others',
    'kompa': 'Others',
    'kraut rock': 'Rock',
    'kuduro': 'Others',
    'kurdish folk': 'Country/Folk',
    'kwaito': 'Others',
    'la indie': 'Indie',
    'laboratorio': 'Experimental',
    'laiko': 'Others',
    'latin': 'Others',
    'latin alternative': 'Others',
    'latin christian': 'Others',
    'latin christmas': 'Others',
    'latin electronica': 'Electronic',
    'latin hip hop': 'Hip-Hop',
    'latin jazz': 'Jazz',
    'latin metal': 'Rock',
    'latin pop': 'Pop',
    'latvian pop': 'Pop',
    'lds': 'Others',
    'leeds indie': 'Indie',
    'levenslied': 'Others',
    'liedermacher': 'Others',
    'light music': 'Others',
    'lilith': 'Others',
    'liquid funk': 'Electronic',
    'lithumania': 'Others',
    'liturgical': 'Classical',
    'lo star': 'Others',
    'lo-fi': 'Indie',
    'louisiana blues': 'Jazz',
    'louisville indie': 'Indie',
    'lounge': 'Others',
    'lounge house': 'Electronic',
    'lovers rock': 'Others',
    'lowercase': 'Experimental',
    'luk thung': 'Others',
    'madchester': 'Rock',
    'maghreb': 'Others',
    'magyar': 'Others',
    'makossa': 'Others',
    'malagasy folk': 'Country/Folk',
    'malaysian pop': 'Pop',
    'mallet': 'Others',
    'mambo': 'Others',
    'mande pop': 'Pop',
    'mandopop': 'Pop',
    'manele': 'Others',
    'marching band': 'Others',
    'mariachi': 'Others',
    'martial industrial': 'Electronic',
    'mashup': 'Others',
    'math pop': 'Indie',
    'math rock': 'Rock',
    'mathcore': 'Rock',
    'mbalax': 'Others',
    'medieval': 'Others',
    'medieval rock': 'Rock',
    'meditation': 'Others',
    'melancholia': 'Others',
    'melbourne bounce': 'Electronic',
    'mellow gold': 'Others',
    'melodic death metal': 'Rock',
    'melodic hard rock': 'Rock',
    'melodic hardcore': 'Rock',
    'melodic metalcore': 'Rock',
    'melodic power metal': 'Rock',
    'melodic progressive metal': 'Rock',
    'memphis blues': 'Jazz',
    'memphis hip hop': 'Hip-Hop',
    'memphis soul': 'RnB/Soul',
    'merengue': 'Others',
    'merengue urbano': 'Others',
    'merseybeat': 'Rock',
    'metal': 'Rock',
    'metal guitar': 'Rock',
    'metalcore': 'Rock',
    'metropopolis': 'Pop',
    'mexican indie': 'Indie',
    'mexican rock-and-roll': 'Rock',
    'mexican son': 'Others',
    'mexican traditional': 'Others',
    'miami bass': 'Hip-Hop',
    'michigan indie': 'Indie',
    'microhouse': 'Electronic',
    'military band': 'Others',
    'minimal': 'Electronic',
    'minimal dub': 'Electronic',
    'minimal dubstep': 'Electronic',
    'minimal melodic techno': 'Electronic',
    'minimal tech house': 'Electronic',
    'minimal techno': 'Electronic',
    'minimal wave': 'Electronic',
    'mizrahi': 'Others',
    'mod revival': 'Rock',
    'modern blues': 'Jazz',
    'modern classical': 'Classical',
    'modern country rock': 'Country/Folk',
    'modern downshift': 'Others',
    'modern free jazz': 'Jazz',
    'modern performance': 'Others',
    'modern southern rock': 'Rock',
    'modern uplift': 'Others',
    'monastic': 'Others',
    'moombahton': 'Electronic',
    'morna': 'Others',
    'motivation': 'Others',
    'motown': 'RnB/Soul',
    'movie tunes': 'Soundtracks',
    'mpb': 'Pop',
    'musica para ninos': 'Others',
    'musiikkia lapsille': 'Others',
    'musique concrete': 'Experimental',
    'musique pour enfants': 'Others',
    'muziek voor kinderen': 'Others',
    'nasheed': 'Others',
    'nashville sound': 'Country/Folk',
    'native american': 'Others',
    'necrogrind': 'Rock',
    'neo classical metal': 'Rock',
    'neo honky tonk': 'Country/Folk',
    'neo mellow': 'Pop',
    'neo metal': 'Rock',
    'neo soul': 'RnB/Soul',
    'neo soul-jazz': 'Jazz',
    'neo-industrial rock': 'Rock',
    'neo-pagan': 'Others',
    'neo-progressive': 'Rock',
    'neo-psychedelic': 'Rock',
    'neo-rockabilly': 'Rock',
    'neo-singer-songwriter': 'Indie',
    'neo-synthpop': 'Pop',
    'neo-trad metal': 'Rock',
    'neo-traditional country': 'Country/Folk',
    'neoclassical': 'Classical',
    'neofolk': 'Others',
    'nepali': 'Others',
    'nerdcore': 'Hip-Hop',
    'neue deutsche harte': 'Rock',
    'neue deutsche welle': 'Pop',
    'neurofunk': 'Electronic',
    'neurostep': 'Electronic',
    'new age': 'Others',
    'new age piano': 'Others',
    'new americana': 'Country/Folk',
    'new beat': 'Electronic',
    'new jack smooth': 'RnB/Soul',
    'new jack swing': 'RnB/Soul',
    'new orleans blues': 'Jazz',
    'new orleans jazz': 'Jazz',
    'new rave': 'Electronic',
    'new romantic': 'Pop',
    'new tribe': 'Others',
    'new wave': 'Pop',
    'new wave pop': 'Pop',
    'new weird america': 'Indie',
    'ninja': 'Others',
    'nintendocore': 'Rock',
    'nl folk': 'Country/Folk',
    'no wave': 'Rock',
    'noise': 'Experimental',
    'noise pop': 'Indie',
    'noise punk': 'Rock',
    'noise rock': 'Rock',
    'nordic folk': 'Country/Folk',
    'nordic house': 'Electronic',
    'norteno': 'Others',
    'northern irish indie': 'Indie',
    'northern soul': 'RnB/Soul',
    'norwegian gospel': 'Others',
    'norwegian hip hop': 'Hip-Hop',
    'norwegian jazz': 'Jazz',
    'norwegian metal': 'Rock',
    'norwegian pop': 'Pop',
    'norwegian punk': 'Rock',
    'norwegian rock': 'Rock',
    'nu age': 'Others',
    'nu disco': 'Electronic',
    'nu electro': 'Electronic',
    'nu gaze': 'Indie',
    'nu jazz': 'Jazz',
    'nu metal': 'Rock',
    'nu skool breaks': 'Electronic',
    'nu-cumbia': 'Others',
    'nueva cancion': 'Others',
    'nursery': 'Others',
    'nwobhm': 'Rock',
    'nwothm': 'Rock',
    'nz indie': 'Indie',
    'oi': 'Rock',
    'old school hip hop': 'Hip-Hop',
    'old-time': 'Country/Folk',
    'opera': 'Classical',
    'operatic pop': 'Pop',
    'opm': 'Pop',
    'oratory': 'Classical',
    'orchestral': 'Classical',
    'organic ambient': 'Electronic',
    'orgcore': 'Rock',
    'orquesta tipica': 'Others',
    'orquesta tropical': 'Others',
    'oshare kei': 'Others',
    'ostrock': 'Rock',
    'outer hip hop': 'Hip-Hop',
    'outlaw country': 'Country/Folk',
    'outsider': 'Experimental',
    'outsider house': 'Electronic',
    'p funk': 'Funk',
    'pagan black metal': 'Rock',
    'pagode': 'Others',
    'pakistani pop': 'Pop',
    'permanent wave': 'Rock',
    'persian pop': 'Pop',
    'persian traditional': 'Others',
    'perth indie': 'Indie',
    'peruvian rock': 'Rock',
    'piano blues': 'Jazz',
    'piano rock': 'Rock',
    'piedmont blues': 'Jazz',
    'pipe band': 'Others',
    'poetry': 'Others',
    'polish hip hop': 'Hip-Hop',
    'polish indie': 'Indie',
    'polish jazz': 'Jazz',
    'polish pop': 'Pop',
    'polish punk': 'Rock',
    'polish reggae': 'Others',
    'polka': 'Others',
    'polynesian pop': 'Pop',
    'polyphony': 'Classical',
    'pop': 'Pop',
    'pop christmas': 'Pop',
    'pop emo': 'Pop',
    'pop house': 'Electronic',
    'pop punk': 'Rock',
    'pop rap': 'Hip-Hop',
    'pop rock': 'Rock',
    'popgaze': 'Indie',
    'porro': 'Others',
    'portland indie': 'Indie',
    'portuguese pop': 'Pop',
    'portuguese rock': 'Rock',
    'post rock': 'Rock',
    'post-disco': 'Electronic',
    'post-disco soul': 'RnB/Soul',
    'post-grunge': 'Rock',
    'post-hardcore': 'Rock',
    'post-metal': 'Rock',
    'post-post-hardcore': 'Rock',
    'post-punk': 'Rock',
    'power blues-rock': 'Rock',
    'power electronics': 'Electronic',
    'power metal': 'Rock',
    'power noise': 'Electronic',
    'power pop': 'Pop',
    'power violence': 'Rock',
    'power-pop punk': 'Rock',
    'praise': 'Others',
    'progressive alternative': 'Rock',
    'progressive bluegrass': 'Country/Folk',
    'progressive electro house': 'Electronic',
    'progressive house': 'Electronic',
    'progressive metal': 'Rock',
    'progressive psytrance': 'Electronic',
    'progressive rock': 'Rock',
    'progressive trance': 'Electronic',
    'progressive trance house': 'Electronic',
    'progressive uplifting trance': 'Electronic',
    'protopunk': 'Rock',
    'psych gaze': 'Rock',
    'psychedelic blues-rock': 'Rock',
    'psychedelic rock': 'Rock',
    'psychedelic trance': 'Electronic',
    'psychill': 'Electronic',
    'psychobilly': 'Rock',
    'pub rock': 'Rock',
    'puerto rican rock': 'Rock',
    'punjabi': 'Others',
    'punk': 'Rock',
    'punk blues': 'Rock',
    'punk christmas': 'Rock',
    'punk ska': 'Rock',
    'qawwali': 'Others',
    'quebecois': 'Others',
    'quiet storm': 'RnB/Soul',
    'r&b': 'RnB/Soul',
    'ragga jungle': 'Electronic',
    'ragtime': 'Jazz',
    'rai': 'Others',
    'ranchera': 'Others',
    'rap': 'Hip-Hop',
    'rap metal': 'Rock',
    'rap metalcore': 'Rock',
    'rap rock': 'Rock',
    'raw black metal': 'Rock',
    're:techno': 'Electronic',
    'reading': 'Others',
    'rebetiko': 'Others',
    'reggae': 'Others',
    'reggae fusion': 'Others',
    'reggae rock': 'Rock',
    'reggaeton': 'Others',
    'regional mexican': 'Others',
    'relaxative': 'Others',
    'remix': 'Electronic',
    'renaissance': 'Classical',
    'retro electro': 'Electronic',
    'retro metal': 'Rock',
    'rhythm and boogie': 'RnB/Soul',
    'riddim': 'Others',
    'rio de la plata': 'Others',
    'riot grrrl': 'Rock',
    'rock': 'Rock',
    'rock catala': 'Rock',
    'rock en espanol': 'Rock',
    'rock gaucho': 'Rock',
    'rock noise': 'Rock',
    'rock steady': 'Others',
    'rock-and-roll': 'Rock',
    'rockabilly': 'Rock',
    'romanian pop': 'Pop',
    'romanian rock': 'Rock',
    'romantic': 'Classical',
    'roots reggae': 'Others',
    'roots rock': 'Rock',
    'rumba': 'Others',
    'russian alternative': 'Rock',
    'russian hip hop': 'Hip-Hop',
    'russian pop': 'Pop',
    'russian punk': 'Rock',
    'russian rock': 'Rock',
    'rva indie': 'Indie',
    'salsa': 'Others',
    'salsa international': 'Others',
    'samba': 'Others',
    'saxophone': 'Jazz',
    'schlager': 'Pop',
    'schranz': 'Electronic',
    'scorecore': 'Soundtracks',
    'scottish rock': 'Rock',
    'scratch': 'Hip-Hop',
    'screamo': 'Rock',
    'screamo punk': 'Rock',
    'screamocore': 'Rock',
    'seattle indie': 'Indie',
    'sega': 'Others',
    'serialism': 'Classical',
    'sertanejo': 'Country/Folk',
    'sertanejo tradicional': 'Country/Folk',
    'sertanejo universitario': 'Country/Folk',
    'sevdah': 'Others',
    'shanty': 'Others',
    'sheffield indie': 'Indie',
    'shibuya-kei': 'Pop',
    'shimmer pop': 'Pop',
    'shimmer psych': 'Rock',
    'shiver pop': 'Pop',
    'shoegaze': 'Rock',
    'show tunes': 'Soundtracks',
    'singaporean pop': 'Pop',
    'singer-songwriter': 'Indie',
    'sinhala': 'Others',
    'ska': 'Others',
    'ska punk': 'Rock',
    'ska revival': 'Others',
    'skate punk': 'Rock',
    'skiffle': 'Others',
    'skinhead oi': 'Rock',
    'skinhead reggae': 'Others',
    'skweee': 'Electronic',
    'slam death metal': 'Rock',
    'slash punk': 'Rock',
    'slc indie': 'Indie',
    'sleaze rock': 'Rock',
    'sleep': 'Others',
    'slovak hip hop': 'Hip-Hop',
    'slovak pop': 'Pop',
    'slovenian rock': 'Rock',
    'slow core': 'Rock',
    'sludge metal': 'Rock',
    'smooth jazz': 'Jazz',
    'smooth urban r&b': 'RnB/Soul',
    'soca': 'Others',
    'soda pop': 'Pop',
    'soft rock': 'Rock',
    'solipsynthm': 'Electronic',
    'soukous': 'Others',
    'soul': 'RnB/Soul',
    'soul blues': 'Jazz',
    'soul christmas': 'RnB/Soul',
    'soul flow': 'RnB/Soul',
    'soul jazz': 'Jazz',
    'soundtrack': 'Soundtracks',
    'south african jazz': 'Jazz',
    'southern gospel': 'Others',
    'southern hip hop': 'Hip-Hop',
    'southern rock': 'Rock',
    'southern soul': 'RnB/Soul',
    'southern soul blues': 'Jazz',
    'space rock': 'Rock',
    'spanish classical': 'Classical',
    'spanish folk': 'Others',
    'spanish hip hop': 'Hip-Hop',
    'spanish indie pop': 'Pop',
    'spanish indie rock': 'Rock',
    'spanish invasion': 'Others',
    'spanish new wave': 'Pop',
    'spanish pop': 'Pop',
    'spanish pop rock': 'Rock',
    'spanish punk': 'Rock',
    'spanish reggae': 'Others',
    'speed garage': 'Electronic',
    'speed metal': 'Rock',
    'speedcore': 'Electronic',
    'spoken word': 'Others',
    'spytrack': 'Others',
    'steampunk': 'Others',
    'steelpan': 'Others',
    'stl indie': 'Indie',
    'stomp and flutter': 'Indie',
    'stomp and holler': 'Indie',
    'stomp and whittle': 'Indie',
    'stomp pop': 'Pop',
    'stoner metal': 'Rock',
    'stoner rock': 'Rock',
    'straight edge': 'Rock',
    'street punk': 'Rock',
    'stride': 'Jazz',
    'string band': 'Country/Folk',
    'string folk': 'Country/Folk',
    'string quartet': 'Classical',
    'substep': 'Electronic',
    'sunset lounge': 'Electronic',
    'suomi rock': 'Rock',
    'surf music': 'Rock',
    'swamp blues': 'Jazz',
    'swamp pop': 'Pop',
    'swedish alternative rock': 'Rock',
    'swedish hard rock': 'Rock',
    'swedish hip hop': 'Hip-Hop',
    'swedish indie pop': 'Indie',
    'swedish indie rock': 'Indie',
    'swedish jazz': 'Jazz',
    'swedish metal': 'Rock',
    'swedish pop': 'Pop',
    'swedish pop punk': 'Rock',
    'swedish prog': 'Rock',
    'swedish punk': 'Rock',
    'swedish reggae': 'Others',
    'swedish soft pop': 'Pop',
    'swedish synthpop': 'Pop',
    'swing': 'Jazz',
    'swirl psych': 'Rock',
    'swiss folk': 'Country/Folk',
    'swiss hip hop': 'Hip-Hop',
    'swiss rock': 'Rock',
    'symphonic black metal': 'Rock',
    'symphonic metal': 'Rock',
    'symphonic rock': 'Rock',
    'synthpop': 'Pop',
    'taiwanese pop': 'Pop',
    'talent show': 'Others',
    'tango': 'Others',
    'tech house': 'Electronic',
    'technical brutal death metal': 'Rock',
    'technical death metal': 'Rock',
    'techno': 'Electronic',
    'teen pop': 'Pop',
    'tejano': 'Others',
    'tekno': 'Electronic',
    'terrorcore': 'Electronic',
    'texas blues': 'Jazz',
    'texas country': 'Country/Folk',
    'thai indie': 'Indie',
    'thai pop': 'Pop',
    'thrash core': 'Rock',
    'thrash metal': 'Rock',
    'thrash-groove metal': 'Rock',
    'throat singing': 'Others',
    'tibetan': 'Others',
    'tico': 'Others',
    'timba': 'Others',
    'tin pan alley': 'Others',
    'traditional blues': 'Jazz',
    'traditional british folk': 'Country/Folk',
    'traditional country': 'Country/Folk',
    'traditional folk': 'Country/Folk',
    'traditional funk': 'Funk',
    'traditional irish folk': 'Country/Folk',
    'traditional reggae': 'Others',
    "traditional rock 'n roll": 'Rock',
    'traditional rockabilly': 'Rock',
    'traditional scottish folk': 'Country/Folk',
    'traditional ska': 'Rock',
    'traditional soul': 'RnB/Soul',
    'traditional swing': 'Jazz',
    'trance': 'Electronic',
    'trance hop': 'Electronic',
    'trap music': 'Hip-Hop',
    'trapstep': 'Electronic',
    'trash rock': 'Rock',
    'triangle indie': 'Indie',
    'tribal house': 'Electronic',
    'tribute': 'Others',
    'trip hop': 'Electronic',
    'tropical': 'Others',
    'trova': 'Others',
    'turbo folk': 'Country/Folk',
    'turkish alternative': 'Rock',
    'turkish classical': 'Classical',
    'turkish folk': 'Country/Folk',
    'turkish hip hop': 'Hip-Hop',
    'turkish jazz': 'Jazz',
    'turkish pop': 'Pop',
    'turkish rock': 'Rock',
    'turntablism': 'Hip-Hop',
    'twee indie pop': 'Indie',
    'twee pop': 'Indie',
    'twin cities indie': 'Indie',
    'tzadik': 'Others',
    'uk dub': 'Electronic',
    'uk garage': 'Electronic',
    'uk hip hop': 'Hip-Hop',
    'uk post-punk': 'Rock',
    'ukrainian rock': 'Rock',
    'ukulele': 'Others',
    'unblack metal': 'Rock',
    'underground hip hop': 'Hip-Hop',
    'underground latin hip hop': 'Hip-Hop',
    'underground pop rap': 'Hip-Hop',
    'underground power pop': 'Pop',
    'underground rap': 'Hip-Hop',
    'uplifting trance': 'Electronic',
    'urban contemporary': 'RnB/Soul',
    'vallenato': 'Others',
    'vancouver indie': 'Indie',
    'vapor house': 'Electronic',
    'vaporwave': 'Electronic',
    'vegan straight edge': 'Rock',
    'vegas indie': 'Indie',
    'velha guarda': 'Others',
    'venezuelan rock': 'Rock',
    'video game music': 'Soundtracks',
    'vienna indie': 'Indie',
    'vietnamese pop': 'Pop',
    'viking metal': 'Rock',
    'vintage chanson': 'Others',
    'vintage country folk': 'Country/Folk',
    'vintage gospel': 'Others',
    'vintage jazz': 'Jazz',
    'vintage reggae': 'Others',
    'vintage rockabilly': 'Rock',
    'vintage schlager': 'Others',
    'vintage swedish pop': 'Pop',
    'vintage swing': 'Jazz',
    'vintage swoon': 'Others',
    'vintage tango': 'Jazz',
    'vintage western': 'Country/Folk',
    'violin': 'Classical',
    'viral pop': 'Pop',
    'visual kei': 'Rock',
    'vocal house': 'Electronic',
    'vocal jazz': 'Jazz',
    'vocaloid': 'Pop',
    'volksmusik': 'Others',
    'warm drone': 'Electronic',
    'welsh rock': 'Rock',
    'west african jazz': 'Jazz',
    'west coast rap': 'Hip-Hop',
    'western swing': 'Country/Folk',
    'wind ensemble': 'Classical',
    'witch house': 'Electronic',
    'wonky': 'Electronic',
    'workout': 'Others',
    'world': 'Others',
    'world chill': 'Others',
    'world christmas': 'Jazz',
    'world fusion': 'Jazz',
    'worship': 'Pop',
    'wrestling': 'Others',
    'wrock': 'Rock',
    'ye ye': 'Pop',
    'yoik': 'Others',
    'yugoslav rock': 'Rock',
    'zeuhl': 'Experimental',
    'zillertal': 'Others',
    'zim': 'Others',
    'zolo': 'Experimental',
    'zouglou': 'Others',
    'zouk': 'Others',
    'zydeco': 'Others',
}

def convert(g):
    # Jazz, Funk, RnB/Soul, Classical, Soundtracks, Hip-Hop, Country/Folk, Rock, Indie, Experimental, Electronic, Pop, and Others.
    if (g not in subgenre_to_general_genre) or (subgenre_to_general_genre[g] == 'Others'):
        if 'jazz' in g or 'fusion' in g or 'blues' in g:
            return 'Jazz'
        if 'funk' in g or 'boogie' in g:
            return 'Funk'
        if 'soul' in g or 'r&b' in g or 'disco' in g:
            return 'RnB/Soul'
        if 'movie' in g or 'game' in g or 'soundtrack' in g:
            return 'Soundtracks'
        if 'rap' in g or 'hip hop' in g or 'boom bap' in g:
            return 'Hip-Hop'
        if 'folk' in g or 'country' in g:
            return 'Country/Folk'
        if 'grunge' in g or 'rock' in g or 'punk' in g or 'new wave' in g or 'metal' in g:
            return 'Rock'
        if 'indie' in g or 'alternative' in g:
            return 'Indie'
        if 'avant' in g or 'experimental' in g:
            return 'Experimental'
        if 'house' in g or 'trance' in g or 'bass' in g or 'synth' in g or 'techno' in g or 'electro' in g:
            return 'Electronic'
        if 'pop' in g:
            return 'Pop'
        return 'Others'
    return subgenre_to_general_genre[g]